### ISSUE TITLE
Not able to play VP on devcards

### ISSUE THREAD

**Issue by maxkonrad** [bcollazo/catanatron#280]
```
    # Dev Card Plays
    PLAY_KNIGHT_CARD = "PLAY_KNIGHT_CARD"  # value is None
    PLAY_YEAR_OF_PLENTY = "PLAY_YEAR_OF_PLENTY"  # value is (Resource, Resource)
    PLAY_MONOPOLY = "PLAY_MONOPOLY"  # value is Resource
    PLAY_ROAD_BUILDING = "PLAY_ROAD_BUILDING"  # value is None
```

Here at the enums part of catanatron_core I couldn't see PLAY_VICTORY_POINT or such a naming. Why there isn't one?

**Comment by maxkonrad** [comment]
And if this is a bug can I commit it? this is a good first issue and it will be my first open source contribution.

**Comment by bcollazo** [comment]
Hey @maxkonrad thanks for the interest! I think there isn't one because one doesn't really get to "play" the Victory Point per-se... just by virtue of having it, its "being played" if that makes sense. That is, the game is already keeping track of "public victory points" and "actual victory points" behind the scenes, should that should take them into account!

**Comment by maxkonrad** [comment]
Oh I see, sorry for this. Thanks so much! I think this issue can be closed then.
